### ISSUE TITLE
libkcp 还更新么

### ISSUE THREAD

**Issue by yanchuang12** [xtaci/libkcp#10]
求教， 我看kcp.go 更新了好多内容， 而在libkcp上还是很早的版本， 是更新后有问题么

**Comment by xtaci** [comment]
精力不够啊

**Comment by yanchuang12** [comment]
可以把kcp.go中的内容借鉴过来么， 我看deadlink虽然有判断但是没用，想把deadlink使用起来，者通过重传次数的判断感觉不太合理， 大佬，有好的思路么
