### ISSUE TITLE
这里是不是有bug？

### ISSUE THREAD

**Issue by l42111996** [xtaci/libkcp#12]
https://github.com/xtaci/libkcp/blob/eea90123e99083c2776af07c3c4908f1e733897d/galois_table.c#L22
我看别的版本第一位都是 -1

 -1,    0,    1,   25,    2,   50,   26,  198,

**Comment by zhaowq32** [comment]
https://github.com/jannson/reedsolomon-c 根据这个代码，算出来第一位是255
