### ISSUE TITLE
socket 触发的 SIGPIPE

### ISSUE THREAD

**Issue by horsley** [xtaci/libkcp#2]
已知，向一个已经关闭的 socket 写数据会导致系统发出 SIGPIPE 信号，如果在没有屏蔽掉该信号，iOS 上默认收到这个信号进程就被杀死了，是否需要在 createSession 之后屏蔽 SIGPIPE？

**Comment by xtaci** [comment]
android和ios屏蔽方式不同，肯定是需要屏蔽的。
