### ISSUE TITLE
Another problem in windows.

### ISSUE THREAD

**Issue by PraflyGod** [xtaci/libkcp#4]
I had encountered some problems when I tried to use fec in windows.
some extern variables are not consistent with their delaration.

**Comment by xtaci** [comment]
i'm using CLion c++11 for compiling

**Comment by PraflyGod** [comment]
Yes, I passed the fec test when using g++. But not visual studio 2015. g++ doesn't complain that some extern variables are not consistent with their delaration.

**Comment by xtaci** [comment]
i don't have vs2015 in hand.
