### ISSUE TITLE
作为unity插件使用时，禁用FEC会导致Crash

### ISSUE THREAD

**Issue by HiWill** [xtaci/libkcp#7]
您好！
        我正在尝试把libKcp当做Unity3d插件使用，当使用FEC时能正常工作，禁用FEC却会导致Crash.
unity2017.1.1p3 , mac editor:
初始参数： UDPSession::DialWithOptions("127.0.0.1", 5050, 0,0);

Receiving unhandled NULL exception
Obtained 37 stack frames.
#0  0x00000128f573f9 in UDPSession::out_wrapper(char const*, int, IKCPCB*, void*)
#1  0x00000128f3c3b7 in ikcp_output
#2  0x00000128f3c175 in ikcp_flush
#3  0x00000128f57c0d in UDPSession::Update(unsigned int)
#4  0x00000128f49fa6 in CallMain
#5  0x0000012884220e in  (wrapper managed-to-native) CallNativeCode:CallMain () + 0xbe (0x128842150 0x12884225e) [0x140687000 - Unity Child Domain]
#6  0x0000012884211e in  CallNativeCode:Start () + 0x5e (0x1288420c0 0x128842142)

**Comment by HiWill** [comment]
貌似 Session 的 FEC 初始化在Unity下有问题，把判断是否启用FEC放到Session中解决了问题：https://github.com/HiWill/LibKcpUnity

**Comment by xtaci** [comment]
your PR is welcome
